include: package:very_good_analysis/analysis_options.yaml
linter:
  rules:
    public_member_api_docs: false
    omit_local_variable_types : false
    prefer_final_locals : false
    always_use_package_imports: false
    curly_braces_in_flow_control_structures: false
    avoid_void_async: false